### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MrJudge77** [Systemcluster/The-Witcher-3-Mod-manager#5]
It would be great if you could implement a search feature.

**Comment by Systemcluster** [comment]
Thanks for the suggestion, that should be doable, I'll look into it.

**Comment by Systemcluster** [comment]
I added this in [version `0.7.4`](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases), but I wasn't able to test it with any installed mods yet. Could you check it out and report back?

**Comment by MrJudge77** [comment]
works good. looks good. would be better if it's not case sensitive.

**Comment by MrJudge77** [comment]
Do you mind if I put a link to this github page at nexus mods? or why don't you open up a nexus mods page?

**Comment by Systemcluster** [comment]
> works good. looks good. would be better if it's not case sensitive.

Good point, I changed it to be it case-insensitive in [version 0.7.5](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases). Thanks for testing!

>Do you mind if I put a link to this github page at nexus mods? or why don't you open up a nexus mods page?

Initially i was hoping I could merge my work with stefan3372 so he could update it on his Nexus Mods page, instead of creating a new one. Unfortunately he hasn't responded to my PR and my mails, so maybe I might just create one. I'll think about it.

**Comment by MrJudge77** [comment]
Yeah, I think you should really consider this. You've been a tremendous
help.

I'm also learning how to program python. Any tips?
