### ISSUE TITLE
installed.xml not reading in/formatting xml variables correctly

### ISSUE THREAD

**Issue by MrJudge77** [Systemcluster/The-Witcher-3-Mod-manager#6]
Just noticed this.
Not sure when it started. Doesn't seem to affect gameplay, but I could be wrong.

![image](https://user-images.githubusercontent.com/43927826/61167166-00814180-a56d-11e9-82b6-d9882ad69dd6.png)

![image](https://user-images.githubusercontent.com/43927826/61167183-44744680-a56d-11e9-95e1-6e1ac07792e5.png)

**Comment by Systemcluster** [comment]
Thank you very much for the report! You're right that it doesn't affect gameplay since these are only stored and displayed internally, but it shouldn't happen regardless. This is fixed in [version 0.7.5](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases). Unfortunately the fix only works for mods added after the update for now.

While looking into it I also noticed that new entries in user.settings aren't written correctly sometimes, that is fixed as well, and there existing entries are being corrected automatically the next time the mod manager is opened.
